### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by BollingerInternational** [goodbomb/angular-gulp-browserify-starter#35]
Hello. I see that you're not focusing on angular at this moment but I need to do a quick mod using this app. I appreciate your help. I see that you have used npm mongodb module. Can you give me a quick syntax on implementing it and where in the app it goes? Just a simple connect so the entire app can use it.

**Comment by goodbomb** [comment]
Sorry @BollingerInternational, this project is unmaintained these days. I've long since moved on to React. Not sure why you think I can help with mongoDB as this project doesn't use it at all. Regardless, you would connect to mongoDB using a back end service, not Angular. Connecting to a DB directly from your FE application is extremely dangerous.

**Comment by BollingerInternational** [comment]
Ben,

Thank you. I started looking at Vue.js for my new project.


Sincerely,

*August Bollinger*
(775) 273-8010

Life can be absolutely phenomenal. And it should be. And it WILL be! :)
