### ISSUE TITLE
When javascript  syntax Error occur the gulp will not show the error  and not start the app

### ISSUE THREAD

**Issue by ibrahimmt** [goodbomb/angular-gulp-browserify-starter#36]
![image](https://cloud.githubusercontent.com/assets/8084798/21421719/66d35286-c85a-11e6-90bf-685d916499a9.png)

not starting the project

**Comment by goodbomb** [comment]
Sorry @ibrahimmt, there's probably a strong chance that the latest npm modules are causing errors due to compatibility issues. A lot has likely changed over the last 2 years since I actively maintained this project. I've long since moved on to using React. Unfortunately I don't have time to bring this project up-to-date, especially since Angular 1.x is on its way out. You'd be better off taking the time to learn Angluar 2, React, or Vue. Cheers!
