### ISSUE TITLE
images

### ISSUE THREAD

**Issue by BollingerInternational** [goodbomb/angular-gulp-browserify-starter#7]
Hello,
Thank you for the great work you have done. My issue is with images. I added the assets/images directory but the build is not bringing the images aboard and there are no errors I can see that would help me otherwise. Can you please suggest a remedy? Thank you.

**Comment by BollingerInternational** [comment]
it seems to be a MIME type thing

**Comment by goodbomb** [comment]
Which build run are you using? You will have to run ```gulp build``` to do a full re-build of your /dist directory. If you take a look at the bottom of the ```gulpfile.js``` you will see the tasks that you can execute.

```
gulp.task('build-dev', function(callback) {
    runSequence(
        ['clean-dev', 'lint'],
        // images and vendor tasks are removed to speed up build time. Use "gulp build" to do a full re-build of the dev app.
        ['bundle-dev', 'styles-dev', 'copyIndex', 'copyFavicon'],
        ['devServer', 'watch'],
        callback
    );
});
```

You'll notice that the default task doesn't include any static assets. The main reason for this is due to speed. If you have a lot of images, you don't want to have to delete them and re-copy them over to the dist folder every time you change a file. So I set it up so that if you add new static files (images, fonts, etc), then you have to re-build the dist folder using the ```gulp build``` command.

Try that and see if it works.

**Comment by BollingerInternational** [comment]
Thank you for the quick response. I tried the gulp build earlier after reading your notes a little closer and the dist directory does have the images, but the problem is this message I get in the console. Resource interpreted as Image but transferred with MIME type text/html:

**Comment by goodbomb** [comment]
I just googled it quick and this answer came up: http://stackoverflow.com/questions/8057030/resource-interpreted-as-image-but-transferred-with-mime-type-text-html-magento

"This might well occur if your image path is set incorrectly. For example relative to current directory "images/myimage.gif" vs relative to web root "/images/myimage.gif"."

Are you referencing the correct location for your images? You have to remember that when you're adding image paths to your CSS and HTML files (and anywhere else in your application), you need make sure that the path is relative to your /dist folder and not your /app folder. So the relative path for your images should always be ```/images/some_image.jpg```

**Comment by BollingerInternational** [comment]
Excellent! That worked splendidly. Thank you :)
