### ISSUE TITLE
Problem setting up crawlme

### ISSUE THREAD

**Issue by BollingerInternational** [goodbomb/angular-gulp-browserify-starter#9]
How would I go about setting up the npm module "crawlme" in your framework? I have a LAMP stack on AWS with nodeJS also installed. I placed crawlme in node_modules using npm. I am essentially ftping the dist folder to the web root. I then use the Fetch As Googlebot tool and although I can see the pages render, the googlebot tool shows a 404. Here is my server.js file:

var express = require('express'),
    crawlme = require('crawlme'),
    url     = require('url'),
    proxy   = require('proxy-middleware'),
    server  = express(),
    API_URL = process.env.API_URL || 'http://localhost:3000/';

server.set('port', (process.env.PORT || 5000));
server.use(crawlme({waitFor: 2000}));
server.use(express.static(__dirname + '/dist'));

server.listen(server.get('port'), function() {
  console.log("Node app is running at localhost:" + server.get('port'));
});

// Proxy settings for connecting to API
// process.env.API_URL is an environment variable set on Heroku
server.use('/api', proxy(url.parse(API_URL)));

**Comment by goodbomb** [comment]
Sorry for the late response. My hosting provider royally f'd up and my primary email address has been out of service for a month.

Unfortunately I don't think I'll be able to help much. I've never used crawlme before, but honestly, I don't think you really need it. As of May 2014, Google's indexing algorithm started executing javascript on webpages, specifically because so many sites out there are being built with javascript frameworks. You don't need a tool like crawlme anymore (and from the looks of it it isn't actively maintained anymore).

Here's the announcement: http://googlewebmastercentral.blogspot.no/2014/05/understanding-web-pages-better.html
